// GENERATED by @gel/generate v0.6.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $AuditLogλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "resource": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "resourceId": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "userAgent": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "action": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "ipAddress": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "newValues": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "oldValues": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "user": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $AuditLog = $.ObjectType<"default::AuditLog", $AuditLogλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::AuditLog">;
const $AuditLog = $.makeType<$AuditLog>(_.spec, "4beccd05-4cf7-11f0-8cf3-9f46070d9b33", _.syntax.literal);

const AuditLog: $.$expr_PathNode<$.TypeSet<$AuditLog, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AuditLog, $.Cardinality.Many), null);

export type $PermissionλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "action": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "resource": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "roles": $.LinkDesc<$Role, $.Cardinality.Many, {}, false, true,  false, false>;
  "<permissions[is Role]": $.LinkDesc<$Role, $.Cardinality.Many, {}, false, false,  false, false>;
  "<permissions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Permission = $.ObjectType<"default::Permission", $PermissionλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {resource: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },action: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {name: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Permission">;
const $Permission = $.makeType<$Permission>(_.spec, "4c0a29e7-4cf7-11f0-bf66-11096195942a", _.syntax.literal);

const Permission: $.$expr_PathNode<$.TypeSet<$Permission, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Permission, $.Cardinality.Many), null);

export type $RoleλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "permissions": $.LinkDesc<$Permission, $.Cardinality.Many, {}, false, false,  false, false>;
  "users": $.LinkDesc<$User, $.Cardinality.Many, {}, false, true,  false, false>;
  "<roles[is Permission]": $.LinkDesc<$Permission, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Role = $.ObjectType<"default::Role", $RoleλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {name: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Role">;
const $Role = $.makeType<$Role>(_.spec, "4c22a322-4cf7-11f0-bdb7-59204f154361", _.syntax.literal);

const Role: $.$expr_PathNode<$.TypeSet<$Role, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Role, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "passwordResetToken": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "emailVerificationToken": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "username": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "avatarUrl": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "emailVerifiedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "firstName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "lastName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "fullName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, true, false, false>;
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "isVerified": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "lastLoginAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "passwordHash": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "passwordResetExpires": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "updatedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "roles": $.LinkDesc<$Role, $.Cardinality.Many, {}, false, false,  false, false>;
  "sessions": $.LinkDesc<$UserSession, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user[is AuditLog]": $.LinkDesc<$AuditLog, $.Cardinality.Many, {}, false, false,  false, false>;
  "<users[is Role]": $.LinkDesc<$Role, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user[is UserSession]": $.LinkDesc<$UserSession, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<users": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {username: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {email: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::User">;
const $User = $.makeType<$User>(_.spec, "4bf4252b-4cf7-11f0-b583-7b763b8e4edd", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $UserSessionλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "sessionToken": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "refreshToken": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, true, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "expiresAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "ipAddress": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "lastAccessedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "userAgent": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "user": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "<sessions[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sessions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $UserSession = $.ObjectType<"default::UserSession", $UserSessionλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {refreshToken: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {sessionToken: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::UserSession">;
const $UserSession = $.makeType<$UserSession>(_.spec, "4c489eee-4cf7-11f0-a0bd-9fa460ff4fdc", _.syntax.literal);

const UserSession: $.$expr_PathNode<$.TypeSet<$UserSession, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserSession, $.Cardinality.Many), null);



export { $AuditLog, AuditLog, $Permission, Permission, $Role, Role, $User, User, $UserSession, UserSession };

type __defaultExports = {
  "AuditLog": typeof AuditLog;
  "Permission": typeof Permission;
  "Role": typeof Role;
  "User": typeof User;
  "UserSession": typeof UserSession
};
const __defaultExports: __defaultExports = {
  "AuditLog": AuditLog,
  "Permission": Permission,
  "Role": Role,
  "User": User,
  "UserSession": UserSession
};
export default __defaultExports;
